USE STORE;

CREATE TABLE PROSPECTO(
IDPROSPECTO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDOPAT VARCHAR(20) NOT NULL,
APELLIDOMAT VARCHAR(20) ,
CALLE VARCHAR(40) NOT NULL,
NUMERO VARCHAR(4) NOT NULL,
COLONIA VARCHAR(30) NOT NULL,
CP VARCHAR(5) NOT NULL,
TELEFONO VARCHAR(10) NOT NULL,
RFC VARCHAR(13) NOT NULL,
ESTATUS VARCHAR(10) NOT NULL,
OBSERVACIONES VARCHAR(100)
);
CREATE TABLE DOCUMENTO(
ID INT AUTO_INCREMENT PRIMARY KEY,
IDPROSPECTO INT NOT NULL,
IDDOCUMENTO INT NOT NULL,
NOMBREDOC VARCHAR(20) NOT NULL,
DOCUMENTO LONGTEXT NOT NULL
);

ALTER TABLE DOCUMENTO ADD CONSTRAINT FK_PROSP_DOC FOREIGN KEY (IDPROSPECTO) REFERENCES PROSPECTO(IDPROSPECTO);